[package]
name = "token_merge"
version = "0.0.0"
authors = [ "catalin-neagu <catalin.neagu@elrond.com>",]
edition = "2018"

[lib]
path = "src/token_merge.rs"

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.elrond-wasm]
version = "0.22.6"
